[dns]
port = 15353
protocol = "udp"

    [dns.domain]
    response_type = "NxError"
    domain = "ipv6.ellefsen.ninja"
    prefix = "2600:70ff:e861::"
    mask = 48

    [dns.soa]
    ttl = 300
    refresh = 3600
    retry = 1800
    expire = 10800
    minimum = 300
    mname = "ns-ipv6.ellefsen.ninja"
    rname = "dns.ellefsen.ninja"

    [dns.ns]
    servers = ["ns-ipv6.ellefsen.ninja"]

[subdomains]
    [subdomains."dynamic.ipv6.ellefsen.ninja"]
    response_type = "Dynamic"
    prefix = "2600:70ff:e861:1::"
    mask = 64
