name: go-dns
version: git
summary: A simple dynamic DNS server for dynamic IPv6 addresses
description: |
  A simple dynamic DNS server that create dynamic dns names for IPV6 addresses
  based on the address itself.
grade: devel
base: core22

confinement: strict

parts:
  go-dns:
    plugin: go
    source: .
    source-type: local
    build-snaps:
      - go

apps:
  go-dns:
    daemon: simple
    restart-condition: always
    plugs:
      - network
    command: go-dns